GET http://localhost:8080/api/employees

###

POST http://localhost:8080/api/employees/register
Content-Type: multipart/form-data

{
  "grade": "programmer",
  "n

###

PUT http://localhost:8080/api/employees
Content-Type: application/json

{
  "id": 1,
  "name": "soltan",
  "surname": "sunnetbayev",
  "password": "pass2",
  "grade": "programmer"
}

###

DELETE http://localhost:8080/api/employees/1/id

###

GET http://localhost:8080/api/products

###

POST http://localhost:8080/api/products/addOrEditProduct
Content-Type: application/json

{
  
}

###

PUT http://localhost:8080/api/products/updateProduct
Content-Type: application/json

{
  "id": 5,
  "name": "cola",
  "amount": 16,
  "takenPrice": 343,
  "sellPrice": 234,
  "code": "qwerty"
}